Repository E3SM-Project/polaris, pull requests merged in 2023-09, with the labels that each got.

#112 Add timers to steps as they run in a suite or task
  polaris/run/serial.py
Labels: clean-up, framework

#113 Reorganize validation
  docs/developers_guide/api.md
  docs/developers_guide/docs.md
  docs/developers_guide/framework/commands.md
  docs/developers_guide/framework/validation.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/tasks/baroclinic_channel.md
  docs/developers_guide/organization/categories_of_tasks.md
  docs/developers_guide/organization/tasks.md
  docs/developers_guide/seaice/api.md
  polaris/io.py
  polaris/ocean/tasks/baroclinic_channel/baroclinic_channel_test_case.py
  polaris/ocean/tasks/baroclinic_channel/decomp/__init__.py
  polaris/ocean/tasks/baroclinic_channel/default/__init__.py
  polaris/ocean/tasks/baroclinic_channel/forward.py
  polaris/ocean/tasks/baroclinic_channel/init.py
  polaris/ocean/tasks/baroclinic_channel/restart/__init__.py
  polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
  polaris/ocean/tasks/baroclinic_channel/threads/__init__.py
  polaris/ocean/tasks/baroclinic_channel/validate.py
  polaris/ocean/tasks/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tasks/global_convergence/cosine_bell/forward.py
  polaris/ocean/tasks/inertial_gravity_wave/convergence/__init__.py
  polaris/ocean/tasks/inertial_gravity_wave/forward.py
  polaris/ocean/tasks/manufactured_solution/convergence/__init__.py
  polaris/ocean/tasks/manufactured_solution/forward.py
  polaris/ocean/tasks/single_column/cvmix/__init__.py
  polaris/ocean/tasks/single_column/forward.py
  polaris/ocean/tasks/single_column/ideal_age/__init__.py
  polaris/run/serial.py
  polaris/seaice/tasks/single_column/__init__.py
  polaris/seaice/tasks/single_column/exact_restart/__init__.py
  polaris/seaice/tasks/single_column/exact_restart/validate.py
  polaris/seaice/tasks/single_column/forward.py
  polaris/seaice/tasks/single_column/standard_physics/__init__.py
  polaris/setup.py
  polaris/step.py
  polaris/task.py
  polaris/validate.py
Labels: clean-up, framework, ocean, sea ice

#116 Add support for shared steps
  polaris/cache.py
  polaris/component.py
  polaris/io.py
  polaris/list.py
  polaris/mesh/spherical.py
  polaris/model_step.py
  polaris/ocean/model/ocean_model_step.py
  polaris/ocean/resolution.py
  polaris/ocean/tasks/baroclinic_channel/__init__.py
  polaris/ocean/tasks/baroclinic_channel/baroclinic_channel_test_case.py
  polaris/ocean/tasks/baroclinic_channel/decomp/__init__.py
  polaris/ocean/tasks/baroclinic_channel/default/__init__.py
  polaris/ocean/tasks/baroclinic_channel/forward.py
  polaris/ocean/tasks/baroclinic_channel/init.py
  polaris/ocean/tasks/baroclinic_channel/restart/__init__.py
  polaris/ocean/tasks/baroclinic_channel/restart/restart_step.py
  polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
  polaris/ocean/tasks/baroclinic_channel/rpe/analysis.py
  polaris/ocean/tasks/baroclinic_channel/threads/__init__.py
  polaris/ocean/tasks/baroclinic_channel/validate.py
  polaris/ocean/tasks/baroclinic_channel/viz.py
  polaris/ocean/tasks/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tasks/global_convergence/cosine_bell/analysis.py
  polaris/ocean/tasks/global_convergence/cosine_bell/forward.py
  polaris/ocean/tasks/global_convergence/cosine_bell/init.py
  polaris/ocean/tasks/global_convergence/cosine_bell/viz.py
  polaris/ocean/tasks/inertial_gravity_wave/analysis.py
  polaris/ocean/tasks/inertial_gravity_wave/convergence/__init__.py
  polaris/ocean/tasks/inertial_gravity_wave/forward.py
  polaris/ocean/tasks/inertial_gravity_wave/init.py
  polaris/ocean/tasks/inertial_gravity_wave/viz.py
  polaris/ocean/tasks/manufactured_solution/analysis.py
  polaris/ocean/tasks/manufactured_solution/convergence/__init__.py
  polaris/ocean/tasks/manufactured_solution/forward.py
  polaris/ocean/tasks/manufactured_solution/init.py
  polaris/ocean/tasks/manufactured_solution/viz.py
  polaris/ocean/tasks/single_column/cvmix/__init__.py
  polaris/ocean/tasks/single_column/forward.py
  polaris/ocean/tasks/single_column/ideal_age/__init__.py
  polaris/ocean/tasks/single_column/init.py
  polaris/ocean/tasks/single_column/viz.py
  polaris/remap/mapping_file_step.py
  polaris/run/__init__.py
  polaris/run/serial.py
  polaris/seaice/tasks/single_column/exact_restart/__init__.py
  polaris/seaice/tasks/single_column/exact_restart/validate.py
  polaris/seaice/tasks/single_column/forward.py
  polaris/seaice/tasks/single_column/standard_physics/__init__.py
  polaris/seaice/tasks/single_column/standard_physics/viz.py
  polaris/setup.py
  polaris/step.py
  polaris/suite.py
  polaris/task.py
Labels: enhancement, clean-up, framework, ocean, sea ice

#109 New shared steps capability design doc
  docs/design_docs/index.md
  docs/design_docs/shared_steps.md
Labels: documentation

#121 Update to `mpas_tools` v0.23.0
  deploy/default.cfg
  polaris/mesh/spherical.py
  polaris/viz/__init__.py
Labels: clean-up, deployment, ocean

#122 Fix detecting step already added to task
  polaris/task.py
Labels: bug, framework

#123 Clean up RPE analysis step and framework
  polaris/ocean/rpe.py
  polaris/ocean/tasks/baroclinic_channel/baroclinic_channel.cfg
  polaris/ocean/tasks/baroclinic_channel/forward.py
  polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
  polaris/ocean/tasks/baroclinic_channel/rpe/analysis.py
  polaris/ocean/tasks/cosine_bell/__init__.py
  polaris/ocean/tasks/cosine_bell/analysis.py
Labels: bug, clean-up, ocean

#124 Updates for pyremap >= 1.1.0
  deploy/conda-dev-spec.template
  polaris/remap/mapping_file_step.py
Labels: enhancement, clean-up, deployment, framework

#119 Add shared ocean framework for spherical convergence tests
  docs/developers_guide/framework/config.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/framework.md
  docs/developers_guide/ocean/tasks/cosine_bell.md
  docs/developers_guide/organization/tasks.md
  docs/users_guide/ocean/tasks/cosine_bell.md
  polaris/ocean/convergence/__init__.py
  polaris/ocean/convergence/spherical/__init__.py
  polaris/ocean/convergence/spherical/forward.py
  polaris/ocean/convergence/spherical/spherical.cfg
  polaris/ocean/model/__init__.py
  polaris/ocean/model/time.py
  polaris/ocean/tasks/cosine_bell/__init__.py
  polaris/ocean/tasks/cosine_bell/analysis.py
  polaris/ocean/tasks/cosine_bell/cosine_bell.cfg
  polaris/ocean/tasks/cosine_bell/forward.py
  polaris/ocean/tasks/cosine_bell/forward.yaml
  polaris/ocean/tasks/cosine_bell/init.py
  polaris/ocean/tasks/cosine_bell/viz.py
  polaris/setup.py
Labels: enhancement, ocean
