Repository E3SM-Project/polaris, pull requests merged in 2023-08, with the labels that each got.

#107 Add a polaris logo
  README.md
  docs/_static/polaris_logo_rect.png
  docs/index.md
Labels: documentation

#106 Modularization and cleanup
  docs/developers_guide/api.md
  polaris/run/__init__.py
  polaris/run/serial.py
Labels: clean-up, framework

#105 Fix dependencies in inertial gravity wave convergence test
  polaris/ocean/tests/inertial_gravity_wave/init.py
Labels: bug, ocean
