Repository E3SM-Project/polaris, pull requests merged in 2023-06, with the labels that each got.

#52 Make ocean ntasks and min_tasks a multiple of 4
  polaris/ocean/model/ocean_model_step.py
Labels: clean-up, ocean

#66 Add surface forcing and restoring to single_column test group
  docs/developers_guide/ocean/test_groups/single_column.md
  docs/users_guide/ocean/test_groups/images/single_column_salinity_10day.png
  docs/users_guide/ocean/test_groups/images/single_column_temperature_10day.png
  docs/users_guide/ocean/test_groups/single_column.md
  polaris/ocean/tests/single_column/forward.py
  polaris/ocean/tests/single_column/forward.yaml
  polaris/ocean/tests/single_column/initial_state.py
  polaris/ocean/tests/single_column/single_column.cfg
Labels: enhancement, ocean

#75 Logger cleanup and clarification
  docs/tutorials/dev_add_test_group.md
  polaris/logging.py
  polaris/run/serial.py
  polaris/step.py
Labels: clean-up

#77 Update guidance on switching between branches
  docs/developers_guide/quick_start.md
Labels: documentation

#76 Check available parallel resources only once
  polaris/default.cfg
  polaris/parallel.py
  polaris/run/serial.py
  polaris/step.py
Labels: framework

#78 Separate creating parallel command and running command
  docs/developers_guide/api.md
  polaris/parallel.py
Labels: framework

#60 Add an ideal age tracer case to the single column test group
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/test_groups/single_column.md
  docs/users_guide/ocean/test_groups/images/single_column_ideal_age_tracer_10day.png
  docs/users_guide/ocean/test_groups/single_column.md
  polaris/ocean/suites/pr.txt
  polaris/ocean/tests/single_column/__init__.py
  polaris/ocean/tests/single_column/ideal_age/__init__.py
  polaris/ocean/tests/single_column/ideal_age/forward.yaml
  polaris/ocean/tests/single_column/initial_state.py
  polaris/ocean/tests/single_column/viz.py
Labels: ocean

#79 Change algorithm for constraining resources
  docs/developers_guide/organization/steps.md
  polaris/step.py
Labels: framework

#82 Fix log filename for steps
  polaris/run/serial.py
Labels: bug, framework

#65 Make versions of cosine bell with and without viz steps
  docs/developers_guide/framework/remapping.md
  docs/developers_guide/ocean/test_groups/global_convergence.md
  docs/users_guide/ocean/test_groups/global_convergence.md
  polaris/ocean/tests/global_convergence/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/viz.py
  polaris/remap/mapping_file_step.py
  polaris/viz/globe.py
Labels: clean-up, ocean

#80 Make pickle file of dependency an input
  polaris/run/serial.py
  polaris/step.py
Labels: framework

#81 Remove unused `check_parallel_system` function
  docs/developers_guide/api.md
  polaris/parallel.py
Labels: clean-up, framework

#83 Get Slurm options in a separate function
  docs/developers_guide/api.md
  polaris/job/__init__.py
Labels: framework

#84 Pull out common setup between run procedures
  docs/developers_guide/api.md
  polaris/run/__init__.py
  polaris/run/serial.py
Labels: clean-up, framework

#87 Rename namelist implicit bottom drag namelist option
  polaris/ocean/tests/baroclinic_channel/forward.yaml
Labels: clean-up, ocean, E3SM PR finished

#86 Ignore nonexistent `step_after_run.pickle` file
  polaris/run/serial.py
Labels: bug

#88 Fix equations in baroclinic channel User's Guide
  docs/users_guide/ocean/test_groups/baroclinic_channel.md
Labels: bug, documentation, ocean

#92 Remove `manufactured_soluiton` test case from suites
  polaris/ocean/suites/nightly.txt
  polaris/ocean/suites/pr.txt
Labels: clean-up, ocean

#90 Reformat command line help descriptions
  deploy/shared.py
  polaris/cache.py
  polaris/list.py
  polaris/run/serial.py
  polaris/setup.py
  polaris/suite.py
  utils/bisect/bisect.py
  utils/bisect/bisect_step.py
  utils/e3sm_update/test_e3sm_changes.py
  utils/matrix/setup_matrix.py
Labels: clean-up, framework, utility

#93 Update step inputs attribute with input filenames
  polaris/step.py
Labels: bug, framework

#94 Fixup cosine bell test: Allow user changes to vert_levels cfg option
  polaris/ocean/tests/global_convergence/cosine_bell/forward.py
Labels: bug, ocean
