Repository E3SM-Project/polaris, pull requests merged in 2023-02, with the labels that each got.

#6 Fix pushing docs to gh-pages
  .github/workflows/docs_workflow.yml
Labels: ci

#7 Fix docs
  .github/workflows/build_workflow.yml
  README.md
  setup.cfg
Labels: documentation, ci

#8 Add a configure script and support files
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  .gitignore
  configure_polaris_envs.py
  deploy/__init__.py
  deploy/albany_supported.txt
  deploy/bootstrap.py
  deploy/conda-dev-spec.template
  deploy/default.cfg
  deploy/dev-spec.txt
  deploy/load_polaris.template
  deploy/petsc_supported.txt
  deploy/shared.py
  deploy/unsupported.txt
  setup.cfg
Labels: ci, deployment

#9 Add config files for supported machines
  deploy/bootstrap.py
  deploy/default.cfg
  polaris/machines/__init__.py
  polaris/machines/anvil.cfg
  polaris/machines/chicoma-cpu.cfg
  polaris/machines/chrysalis.cfg
  polaris/machines/compy.cfg
  polaris/machines/conda-linux.cfg
  polaris/machines/conda-osx.cfg
  polaris/machines/cori-haswell.cfg
  polaris/machines/default.cfg
  polaris/machines/pm-cpu.cfg
Labels: deployment, framework

#11 Fix copying docs
  .github/workflows/docs_workflow.yml
Labels: bug, ci

#12 Fix small README typo
  README.md
Labels: documentation

#13 Add versions side bar
  docs/_static/style.css
  docs/_templates/layout.html
  docs/_templates/versions.html
  docs/conf.py
Labels: documentation

#15 Add more documentation
  deploy/conda-dev-spec.template
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/developers_guide/api.md
  docs/developers_guide/machines/anvil.md
  docs/developers_guide/machines/chicoma.md
  docs/developers_guide/machines/chrysalis.md
  docs/developers_guide/machines/compy.md
  docs/developers_guide/machines/cori.md
  docs/developers_guide/machines/index.md
  docs/developers_guide/machines/perlmutter.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/index.md
  docs/developers_guide/ocean/test_groups/global_convergence.md
  docs/developers_guide/ocean/test_groups/index.md
  docs/index.md
  docs/users_guide/machines/anvil.md
  docs/users_guide/machines/chicoma.md
  docs/users_guide/machines/chrysalis.md
  docs/users_guide/machines/compy.md
  docs/users_guide/machines/cori.md
  docs/users_guide/machines/index.md
  docs/users_guide/machines/perlmutter.md
  polaris/__init__.py
Labels: documentation

#17 Add utilities from compass
  utils/bisect/README.md
  utils/bisect/bisect.py
  utils/bisect/bisect_step.py
  utils/bisect/example.cfg
  utils/e3sm_update/README.md
  utils/e3sm_update/example.cfg
  utils/e3sm_update/test_e3sm_changes.py
  utils/matrix/README.md
  utils/matrix/example.cfg
  utils/matrix/setup_matrix.py
  utils/matrix/shared.py
Labels: utility

#19 Remove namelist and streams from cosine bell init
  polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/analysis.py
  polaris/ocean/tests/global_convergence/cosine_bell/namelist.init
  polaris/ocean/tests/global_convergence/cosine_bell/streams.init
Labels: bug, ocean

#18 Add `polaris cache` command
  deploy/default.cfg
  docs/developers_guide/api.md
  polaris/__main__.py
  polaris/cache.py
  polaris/ocean/cached_files.json
Labels: enhancement, framework

#20 Add `ModelStep` class
  docs/developers_guide/api.md
  docs/developers_guide/framework.md
  docs/developers_guide/organization.md
  polaris/__init__.py
  polaris/mesh/spherical.py
  polaris/model.py
  polaris/model_step.py
  polaris/ocean/suites/cosine_bell_cached_init.txt
  polaris/ocean/tests/global_convergence/cosine_bell/forward.py
  polaris/run/serial.py
  polaris/step.py
Labels: enhancement, framework

#21 Add ocean docs to the User's Guide
  .github/pull_request_template.md
  README.md
  docs/developers_guide/organization.md
  docs/index.md
  docs/users_guide/ocean/framework/index.md
  docs/users_guide/ocean/framework/vertical.md
  docs/users_guide/ocean/index.md
  docs/users_guide/ocean/suites.md
  docs/users_guide/ocean/test_groups/global_convergence.md
  docs/users_guide/ocean/test_groups/images/cosine_bell_convergence.png
  docs/users_guide/ocean/test_groups/index.md
  polaris/ocean/suites/cosine_bell.txt
Labels: documentation, ocean
