Repository E3SM-Project/polaris, pull requests merged in 2023-04, with the labels that each got.

#25 Add test suite guidance to documentation
  docs/developers_guide/organization.md
Labels: documentation

#31 Fix name of configure_polaris_envs.py in docs
  docs/developers_guide/machines/index.md
  docs/developers_guide/quick_start.md
Labels: bug, documentation

#33 Add planar horizontal viz
  docs/developers_guide/api.md
  docs/developers_guide/framework.md
  polaris/ocean/tests/baroclinic_channel/default/__init__.py
  polaris/ocean/tests/baroclinic_channel/initial_state.py
  polaris/ocean/tests/baroclinic_channel/viz.py
  polaris/viz/__init__.py
  polaris/viz/polaris.mplstyle
Labels: enhancement, framework

#36 Add job script to steps
  polaris/setup.py
Labels: enhancement, framework

#38 Reorganize the framework and organization in the developer's guide
  docs/conf.py
  docs/developers_guide/api.md
  docs/developers_guide/docs.md
  docs/developers_guide/framework.md
  docs/developers_guide/framework/commands.md
  docs/developers_guide/framework/config.md
  docs/developers_guide/framework/images/baroclinic_channel_cell_patches.png
  docs/developers_guide/framework/images/baroclinic_channel_edge_patches.png
  docs/developers_guide/framework/index.md
  docs/developers_guide/framework/io.md
  docs/developers_guide/framework/logging.md
  docs/developers_guide/framework/mesh.md
  docs/developers_guide/framework/model.md
  docs/developers_guide/framework/provenance.md
  docs/developers_guide/framework/validation.md
  docs/developers_guide/framework/visualization.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/organization.md
  docs/developers_guide/organization/components.md
  docs/developers_guide/organization/images/org_in_package.png
  docs/developers_guide/organization/images/org_in_work_dir.png
  docs/developers_guide/organization/index.md
  docs/developers_guide/organization/steps.md
  docs/developers_guide/organization/suites.md
  docs/developers_guide/organization/test_cases.md
  docs/developers_guide/organization/test_groups.md
  docs/index.md
Labels: documentation

#39 Add dependencies to Step class
  docs/developers_guide/api.md
  docs/developers_guide/organization/steps.md
  polaris/run/serial.py
  polaris/setup.py
  polaris/step.py
Labels: enhancement, framework

#34 Add global map plots
  docs/conf.py
  docs/developers_guide/api.md
  docs/developers_guide/framework/images/cosine_bell_final.png
  docs/developers_guide/framework/images/cosine_bell_final_land.png
  docs/developers_guide/framework/visualization.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/test_groups/global_convergence.md
  docs/users_guide/ocean/test_groups/global_convergence.md
  polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/cosine_bell.cfg
  polaris/ocean/tests/global_convergence/cosine_bell/viz.py
  polaris/viz/__init__.py
  polaris/viz/globe.py
Labels: framework, ocean

#37 Adjust ny for baroclinic channel to give 500 km domain
  docs/users_guide/ocean/test_groups/baroclinic_channel.md
  polaris/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
  polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
Labels: bug, ocean

#42 Fix bug in changing permissions on downloaded files
  polaris/step.py
Labels: bug, framework

#44 Various pieces of clean-up to the docs
  docs/developers_guide/ocean/models/index.md
  docs/developers_guide/organization/directories.md
  docs/developers_guide/organization/images/org_in_package.png
  docs/developers_guide/organization/index.md
  docs/developers_guide/organization/steps.md
Labels: documentation, clean-up

#43 Use shorter imports for Component, TestGroup, etc.
  docs/developers_guide/framework/remapping.md
  docs/developers_guide/framework/visualization.md
  docs/developers_guide/organization/components.md
  docs/developers_guide/organization/steps.md
  docs/developers_guide/organization/test_cases.md
  docs/developers_guide/organization/test_groups.md
  polaris/components.py
  polaris/mesh/spherical.py
  polaris/ocean/__init__.py
  polaris/ocean/tests/baroclinic_channel/__init__.py
  polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
  polaris/ocean/tests/baroclinic_channel/initial_state.py
  polaris/ocean/tests/baroclinic_channel/rpe_test/analysis.py
  polaris/ocean/tests/baroclinic_channel/viz.py
  polaris/ocean/tests/global_convergence/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
  polaris/ocean/tests/global_convergence/cosine_bell/analysis.py
  polaris/ocean/tests/global_convergence/cosine_bell/init.py
  polaris/ocean/tests/global_convergence/cosine_bell/viz.py
  polaris/remap/mapping_file_step.py
  polaris/setup.py
Labels: documentation, clean-up, framework, ocean

#47 Fix error when building docs on main after merge
  .github/workflows/build_workflow.yml
Labels: bug, ci

#45 Clean up baroclinic channel
  docs/developers_guide/api.md
  docs/developers_guide/framework/mesh.md
  docs/developers_guide/ocean/api.md
  docs/users_guide/ocean/test_groups/baroclinic_channel.md
  polaris/mesh/planar.py
  polaris/ocean/config/output.yaml
  polaris/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
  polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
  polaris/ocean/tests/baroclinic_channel/forward.py
  polaris/ocean/tests/baroclinic_channel/initial_state.py
  polaris/ocean/tests/baroclinic_channel/rpe_test/__init__.py
  polaris/ocean/tests/baroclinic_channel/rpe_test/analysis.py
  polaris/ocean/tests/baroclinic_channel/viz.py
Labels: enhancement, clean-up, framework, ocean

#41 Add User's Guide template for test groups
  docs/developers_guide/docs.md
  docs/users_guide/ocean/test_groups/baroclinic_channel.md
  docs/users_guide/ocean/test_groups/global_convergence.md
  docs/users_guide/ocean/test_groups/template.md
Labels: documentation

#49 Port single column test group
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/test_groups/index.md
  docs/developers_guide/ocean/test_groups/single_column.md
  docs/users_guide/ocean/test_groups/images/single_column_salinity_10day.png
  docs/users_guide/ocean/test_groups/images/single_column_temperature_10day.png
  docs/users_guide/ocean/test_groups/index.md
  docs/users_guide/ocean/test_groups/single_column.md
  polaris/ocean/__init__.py
  polaris/ocean/suites/pr.txt
  polaris/ocean/tests/single_column/__init__.py
  polaris/ocean/tests/single_column/cvmix/__init__.py
  polaris/ocean/tests/single_column/forward.py
  polaris/ocean/tests/single_column/forward.yaml
  polaris/ocean/tests/single_column/initial_state.py
  polaris/ocean/tests/single_column/single_column.cfg
  polaris/ocean/tests/single_column/viz.py
Labels: enhancement, ocean
