Repository E3SM-Project/polaris, pull requests merged in 2024-01, with the labels that each got.

#161 Remove `mamba` command and switch to Miniforge3
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  configure_polaris_envs.py
  deploy/bootstrap.py
  deploy/load_polaris.template
  deploy/shared.py
  docs/developers_guide/deploying_spack.md
  docs/developers_guide/quick_start.md
  docs/tutorials/dev_add_test_group.md
  docs/users_guide/machines/index.md
  docs/users_guide/quick_start.md
  utils/e3sm_update/README.md
Labels: clean-up, deployment

#153 Port ocean internal wave test
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/tasks/index.md
  docs/developers_guide/ocean/tasks/internal_wave.md
  docs/users_guide/ocean/tasks/images/internal_wave_initial_temperature.png
  docs/users_guide/ocean/tasks/index.md
  docs/users_guide/ocean/tasks/internal_wave.md
  polaris/ocean/__init__.py
  polaris/ocean/suites/pr.txt
  polaris/ocean/tasks/internal_wave/__init__.py
  polaris/ocean/tasks/internal_wave/default/__init__.py
  polaris/ocean/tasks/internal_wave/forward.py
  polaris/ocean/tasks/internal_wave/forward.yaml
  polaris/ocean/tasks/internal_wave/init.py
  polaris/ocean/tasks/internal_wave/internal_wave.cfg
  polaris/ocean/tasks/internal_wave/rpe/__init__.py
  polaris/ocean/tasks/internal_wave/rpe/analysis.py
  polaris/ocean/tasks/internal_wave/rpe/forward.yaml
  polaris/ocean/tasks/internal_wave/viz.py
Labels: enhancement, ocean

#156 Add a version check to load script
  deploy/bootstrap.py
  deploy/load_polaris.template
  docs/developers_guide/command_line.md
  docs/developers_guide/quick_start.md
Labels: enhancement, deployment

#169 Update morpheus spack build
  deploy/spack/morpheus_gnu_openmpi.yaml
Labels: deployment

#171 Add dependabot for github actions
  .github/dependabot.yml
Labels: ci

#172 Fix dependabot yaml indentation
  .github/dependabot.yml
Labels: bug, ci

#165 Split spack software and libs
  deploy/bootstrap.py
  docs/developers_guide/deploying_spack.md
  polaris/machines/anvil.cfg
  polaris/machines/chicoma-cpu.cfg
  polaris/machines/chrysalis.cfg
  polaris/machines/compy.cfg
  polaris/machines/morpheus.cfg
  polaris/machines/pm-cpu.cfg
Labels: deployment

#176 Add MOAB to the spack build
  deploy/bootstrap.py
  deploy/default.cfg
Labels: deployment

#178 Update scorpio to v1.4.2
  deploy/default.cfg
Labels: deployment

#168 Add Frontier as a supported machine
  deploy/albany_supported.txt
  deploy/petsc_supported.txt
  docs/developers_guide/machines/frontier.md
  docs/developers_guide/machines/index.md
  docs/users_guide/machines/anvil.md
  docs/users_guide/machines/chicoma.md
  docs/users_guide/machines/chrysalis.md
  docs/users_guide/machines/compy.md
  docs/users_guide/machines/frontier.md
  docs/users_guide/machines/index.md
  docs/users_guide/machines/perlmutter.md
  polaris/machines/frontier.cfg
Labels: deployment

#181 Fix slurm handling of allocatable cores
  polaris/parallel.py
Labels: bug, framework

#180 Fix cores_per_node for Frontier
  polaris/machines/frontier.cfg
Labels: bug, framework
