Repository E3SM-Project/polaris, pull requests merged in 2024-11, with the labels that each got.

#240 Remove git from polaris environment
  deploy/conda-dev-spec.template
Labels: deployment, dependencies

#244 Switch setup configuration to to `pyproject.toml`
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  setup.py
Labels: ci, deployment

#245 Fix small typo in ctest path
  utils/omega/ctest/README.md
Labels: documentation

#241 Add barotropic gyre task
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/tasks/barotropic_gyre.md
  docs/developers_guide/ocean/tasks/index.md
  docs/users_guide/ocean/tasks/barotropic_gyre.md
  docs/users_guide/ocean/tasks/images/barotropic_gyre_forcing.png
  docs/users_guide/ocean/tasks/images/barotropic_gyre_solution.png
  docs/users_guide/ocean/tasks/index.md
  polaris/ocean/__init__.py
  polaris/ocean/tasks/barotropic_gyre/__init__.py
  polaris/ocean/tasks/barotropic_gyre/analysis.py
  polaris/ocean/tasks/barotropic_gyre/barotropic_gyre.cfg
  polaris/ocean/tasks/barotropic_gyre/forward.py
  polaris/ocean/tasks/barotropic_gyre/forward.yaml
  polaris/ocean/tasks/barotropic_gyre/init.py
Labels: ocean

#236 Add convergence tasks for space and time only
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/framework.md
  docs/users_guide/ocean/tasks/cosine_bell.md
  docs/users_guide/ocean/tasks/geostrophic.md
  docs/users_guide/ocean/tasks/inertial_gravity_wave.md
  docs/users_guide/ocean/tasks/manufactured_solution.md
  polaris/ocean/convergence/__init__.py
  polaris/ocean/convergence/analysis.py
  polaris/ocean/convergence/convergence.cfg
  polaris/ocean/convergence/forward.py
  polaris/ocean/convergence/spherical/forward.py
  polaris/ocean/convergence/spherical/spherical.cfg
  polaris/ocean/suites/convergence.txt
  polaris/ocean/suites/geostrophic.txt
  polaris/ocean/suites/nightly.txt
  polaris/ocean/suites/pr.txt
  polaris/ocean/tasks/cosine_bell/__init__.py
  polaris/ocean/tasks/cosine_bell/analysis.py
  polaris/ocean/tasks/cosine_bell/forward.py
  polaris/ocean/tasks/geostrophic/__init__.py
  polaris/ocean/tasks/geostrophic/analysis.py
  polaris/ocean/tasks/geostrophic/forward.py
  polaris/ocean/tasks/inertial_gravity_wave/__init__.py
  polaris/ocean/tasks/inertial_gravity_wave/analysis.py
  polaris/ocean/tasks/inertial_gravity_wave/forward.py
  polaris/ocean/tasks/inertial_gravity_wave/inertial_gravity_wave.cfg
  polaris/ocean/tasks/inertial_gravity_wave/init.py
  polaris/ocean/tasks/manufactured_solution/__init__.py
  polaris/ocean/tasks/manufactured_solution/analysis.py
  polaris/ocean/tasks/manufactured_solution/forward.py
  polaris/ocean/tasks/manufactured_solution/init.py
  polaris/ocean/tasks/manufactured_solution/manufactured_solution.cfg
  polaris/ocean/tasks/sphere_transport/__init__.py
  polaris/ocean/tasks/sphere_transport/analysis.py
  polaris/ocean/tasks/sphere_transport/filament_analysis.py
  polaris/ocean/tasks/sphere_transport/forward.py
  polaris/ocean/tasks/sphere_transport/forward.yaml
  polaris/ocean/tasks/sphere_transport/mixing_analysis.py
  polaris/ocean/tasks/sphere_transport/resources/flow_types.py
Labels: enhancement, ocean
