Repository E3SM-Project/polaris, pull requests merged in 2024-09, with the labels that each got.

#222 Add support for python 3.12
  .github/workflows/build_workflow.yml
  deploy/conda-dev-spec.template
  deploy/default.cfg
  docs/users_guide/quick_start.md
  setup.cfg
Labels: documentation, ci, deployment

#223 Tweak behavior of CI workflows
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
Labels: ci

#224 Add Althea as additional dependabot reviewer
  .github/dependabot.yml
Labels: ci

#226 Add additional flags to `pip install` command in docs and deployment
  configure_polaris_envs.py
  deploy/bootstrap.py
  docs/developers_guide/quick_start.md
Labels: documentation, deployment

#227 Set default model for mpas_to_yaml to mpas-ocean
  polaris/yaml.py
Labels: clean-up

#225 Fixup partition file presence
  docs/developers_guide/framework/model.md
  docs/developers_guide/ocean/api.md
  docs/developers_guide/organization/steps.md
  docs/tutorials/dev_add_test_group.md
  polaris/ocean/convergence/forward.py
  polaris/ocean/ice_shelf/__init__.py
  polaris/ocean/ice_shelf/ssh_forward.py
  polaris/ocean/model/ocean_model_step.py
  polaris/ocean/tasks/baroclinic_channel/decomp/__init__.py
  polaris/ocean/tasks/baroclinic_channel/default/__init__.py
  polaris/ocean/tasks/baroclinic_channel/forward.py
  polaris/ocean/tasks/baroclinic_channel/restart/__init__.py
  polaris/ocean/tasks/baroclinic_channel/restart/restart_step.py
  polaris/ocean/tasks/baroclinic_channel/threads/__init__.py
  polaris/ocean/tasks/cosine_bell/forward.py
  polaris/ocean/tasks/geostrophic/forward.py
  polaris/ocean/tasks/ice_shelf_2d/default/__init__.py
  polaris/ocean/tasks/ice_shelf_2d/forward.py
  polaris/ocean/tasks/inertial_gravity_wave/forward.py
  polaris/ocean/tasks/internal_wave/default/__init__.py
  polaris/ocean/tasks/internal_wave/forward.py
  polaris/ocean/tasks/internal_wave/rpe/__init__.py
  polaris/ocean/tasks/manufactured_solution/forward.py
  polaris/ocean/tasks/manufactured_solution/init.py
  polaris/ocean/tasks/sphere_transport/forward.py
Labels: framework, ocean

#230 Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: ci
