Repository E3SM-Project/polaris, pull requests merged in 2024-07, with the labels that each got.

#195 Update docs link to newer URL style
  README.md
Labels: documentation

#199 Set permissions for Omega CTest downloads
  docs/developers_guide/api.md
  docs/developers_guide/framework/io.md
  polaris/io.py
  polaris/step.py
  utils/omega/ctest/omega_ctest.py
Labels: bug, clean-up, utility

#201 Cull ISOMIP+ planar base mesh
  polaris/ocean/tasks/isomip_plus/__init__.py
  polaris/ocean/tasks/isomip_plus/mesh/planar.py
Labels: clean-up, ocean

#202 Don't smooth ISOMIP+ topography on base mesh
  polaris/ocean/tasks/isomip_plus/__init__.py
Labels: bug, ocean

#203 Add support for creating mapping files with `mbtempest`
  deploy/bootstrap.py
  deploy/conda-dev-spec.template
  docs/developers_guide/framework/remapping.md
  docs/developers_guide/quick_start.md
  docs/developers_guide/troubleshooting.md
  docs/users_guide/quick_start.md
  polaris/model_step.py
  polaris/ocean/tasks/isomip_plus/__init__.py
  polaris/remap/mapping.cfg
  polaris/remap/mapping_file_step.py
  polaris/run/serial.py
  polaris/step.py
Labels: enhancement, framework, ocean

#158 Port ice_shelf_2d test cases
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/framework.md
  docs/developers_guide/ocean/tasks/correlated_tracers_2d.md
  docs/developers_guide/ocean/tasks/divergent_2d.md
  docs/developers_guide/ocean/tasks/geostrophic.md
  docs/developers_guide/ocean/tasks/ice_shelf_2d.md
  docs/developers_guide/ocean/tasks/index.md
  docs/developers_guide/ocean/tasks/nondivergent_2d.md
  docs/developers_guide/ocean/tasks/rotation_2d.md
  docs/users_guide/ocean/framework/ice_shelf.md
  docs/users_guide/ocean/framework/index.md
  docs/users_guide/ocean/tasks/ice_shelf_2d.md
  docs/users_guide/ocean/tasks/images/ice_shelf_2d.png
  docs/users_guide/ocean/tasks/index.md
  polaris/ocean/__init__.py
  polaris/ocean/config/single_layer.yaml
  polaris/ocean/ice_shelf/__init__.py
  polaris/ocean/ice_shelf/ssh_adjustment.cfg
  polaris/ocean/ice_shelf/ssh_adjustment.py
  polaris/ocean/ice_shelf/ssh_forward.py
  polaris/ocean/ice_shelf/ssh_forward.yaml
  polaris/ocean/model/time.py
  polaris/ocean/suites/nightly.txt
  polaris/ocean/suites/pr.txt
  polaris/ocean/tasks/ice_shelf_2d/__init__.py
  polaris/ocean/tasks/ice_shelf_2d/default/__init__.py
  polaris/ocean/tasks/ice_shelf_2d/forward.py
  polaris/ocean/tasks/ice_shelf_2d/forward.yaml
  polaris/ocean/tasks/ice_shelf_2d/global_stats.yaml
  polaris/ocean/tasks/ice_shelf_2d/ice_shelf_2d.cfg
  polaris/ocean/tasks/ice_shelf_2d/init.py
  polaris/ocean/tasks/ice_shelf_2d/ssh_forward.py
  polaris/ocean/tasks/ice_shelf_2d/ssh_forward.yaml
  polaris/ocean/tasks/ice_shelf_2d/tidal_forcing.yaml
  polaris/ocean/tasks/ice_shelf_2d/validate.py
  polaris/ocean/tasks/ice_shelf_2d/viz.py
  polaris/ocean/vertical/__init__.py
  polaris/ocean/vertical/sigma.py
  polaris/ocean/vertical/zlevel.py
  polaris/ocean/vertical/zstar.py
Labels: enhancement, ocean

#207 Add gpus-per-node to job scripts and resources
  docs/developers_guide/api.md
  polaris/job/__init__.py
  polaris/job/job_script.template
  polaris/machines/frontier.cfg
  polaris/machines/pm-gpu.cfg
  polaris/parallel.py
  utils/omega/ctest/job_script.template
  utils/omega/ctest/omega_ctest.py
Labels: enhancement, framework, utility

#206 Fix the `bisect` utility
  polaris/model_step.py
  utils/bisect/bisect_step.py
  utils/bisect/example.cfg
Labels: bug, framework, utility

#208 Remove unused `bashrc` functions
  deploy/shared.py
Labels: clean-up, deployment

#209 Cleanup `configure_polaris_envs.py` and `deploy/shared.py`
  configure_polaris_envs.py
  deploy/shared.py
  deploy/spec-bootstrap.txt
Labels: clean-up, deployment

#210 Standardize styling for all references to Omega
  README.md
  docs/developers_guide/command_line.md
  docs/developers_guide/ocean/index.md
  docs/developers_guide/organization/components.md
  docs/developers_guide/quick_start.md
  docs/glossary.md
  docs/users_guide/ocean/index.md
  docs/users_guide/quick_start.md
  polaris/ocean/mpas_ocean.cfg
  polaris/ocean/ocean.cfg
  polaris/yaml.py
  setup.cfg
Labels: documentation, clean-up

#212 Add link to Omega CTest in Quick Start
  docs/developers_guide/quick_start.md
Labels: documentation
