Repository E3SM-Project/polaris, pull requests merged in 2024-08, with the labels that each got.

#214 Fix deployment on unknown machines
  .github/workflows/build_workflow.yml
  deploy/bootstrap.py
  deploy/default.cfg
  polaris/version.py
Labels: bug, ci, deployment

#215 Fix docs typos and add link to mache docs
  docs/developers_guide/deploying_spack.md
Labels: documentation, clean-up

#218 Change references from `compass` to `polaris`
  deploy/default.cfg
  deploy/shared.py
  docs/developers_guide/ocean/index.md
  docs/developers_guide/ocean/tasks/ice_shelf_2d.md
  docs/developers_guide/organization/tasks.md
  docs/developers_guide/quick_start.md
  polaris/ocean/tasks/internal_wave/viz.py
Labels: clean-up

#217 Remove `polaris clean` from check polaris commands
  deploy/bootstrap.py
Labels: bug, deployment

#219 Fix how yaml model config options are update
  polaris/model_step.py
  polaris/ocean/tasks/manufactured_solution/forward.py
  polaris/yaml.py
Labels: bug, framework, ocean

#216 Bootstrap cleanup
  deploy/bootstrap.py
  deploy/shared.py
Labels: clean-up, deployment
