Repository E3SM-Project/polaris, pull requests merged in 2025-04, with the labels that each got.

#294 Separate dependencies in `pyproject.toml`
  pyproject.toml
Labels: deployment, dependencies

#296 Add a new suite for testing the framework
  docs/developers_guide/ocean/tasks/ice_shelf_2d.md
  docs/tutorials/dev_add_test_group.md
  docs/users_guide/ocean/framework/vertical.md
  docs/users_guide/ocean/suites.md
  polaris/ocean/suites/framework_pr.txt
Labels: enhancement, ocean

#299 Update logo, with a smaller and larger version
  README.md
  docs/_static/polaris_logo_large.png
  docs/_static/polaris_logo_rect.png
  docs/_static/polaris_logo_small.png
  docs/index.md
Labels: documentation

#304 Switch logo in docs to smaller version
  docs/index.md
  docs/logo/polaris_logo_large.png
Labels: documentation

#308 Switch to a custom version dropdown
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  deploy/conda-dev-spec.template
  docs/Makefile
  docs/_static/style.css
  docs/_templates/layout.html
  docs/_templates/versions.html
  docs/conf.py
  docs/developers_guide/building_docs.md
  docs/generate_versions_json.py
  docs/shared/version-switcher.js
  pyproject.toml
Labels: documentation, ci, deployment, dependencies

#309 Update code for version switcher to match pyremap
  docs/shared/version-switcher.js
Labels: bug, documentation
