Repository E3SM-Project/polaris, pull requests merged in 2025-01, with the labels that each got.

#253 Add a cosine-bell decomposition test
  docs/conf.py
  docs/developers_guide/ocean/api.md
  docs/developers_guide/ocean/tasks/barotropic_gyre.md
  docs/developers_guide/ocean/tasks/cosine_bell.md
  docs/tutorials/dev_add_test_group.md
  docs/users_guide/ocean/suites.md
  docs/users_guide/ocean/tasks/cosine_bell.md
  polaris/ocean/suites/cosine_bell.txt
  polaris/ocean/suites/nightly.txt
  polaris/ocean/suites/omega_pr.txt
  polaris/ocean/suites/pr.txt
  polaris/ocean/tasks/cosine_bell/__init__.py
  polaris/ocean/tasks/cosine_bell/decomp.py
Labels: enhancement, ocean

#258 Pre-commit updates and fixes
  .github/workflows/build_workflow.yml
  .pre-commit-config.yaml
Labels: ci

#259 Fix directory permissions not being updated
  deploy/bootstrap.py
Labels: bug, deployment

#260 Add `pre-commit` autoupdate workflow
  .github/workflows/pre_commit_update_workflow.yml
Labels: ci

#264 Temporarily constrain dask
  deploy/conda-dev-spec.template
Labels: dependencies

#263 Add support for amdclang and amdclanggpu on Frontier
  docs/developers_guide/machines/index.md
  docs/developers_guide/quick_start.md
  polaris/machines/frontier.cfg
Labels: enhancement, deployment

#262 Add support for omega sphere transport tests
  polaris/ocean/config/single_layer.yaml
  polaris/ocean/convergence/analysis.py
  polaris/ocean/suites/omega_pr.txt
  polaris/ocean/tasks/sphere_transport/analysis.py
  polaris/ocean/tasks/sphere_transport/correlated_tracers_2d.cfg
  polaris/ocean/tasks/sphere_transport/divergent_2d.cfg
  polaris/ocean/tasks/sphere_transport/forward.py
  polaris/ocean/tasks/sphere_transport/forward.yaml
  polaris/ocean/tasks/sphere_transport/init.py
  polaris/ocean/tasks/sphere_transport/nondivergent_2d.cfg
  polaris/ocean/tasks/sphere_transport/rotation_2d.cfg
  polaris/ocean/tasks/sphere_transport/sphere_transport.cfg
  polaris/ocean/tasks/sphere_transport/viz.py
Labels: ocean

#266 Fix graph file symlink in baroclinic channel RPE test
  polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
Labels: bug, ocean

#267 Fix inertial gravity wave test
  polaris/ocean/tasks/inertial_gravity_wave/__init__.py
  polaris/ocean/tasks/inertial_gravity_wave/forward.yaml
  polaris/ocean/tasks/inertial_gravity_wave/viz.py
Labels: bug, ocean

#269 Exclude latest uxarray 2025.01.0
  deploy/conda-dev-spec.template
  polaris/version.py
Labels: dependencies

#268 Fix refinement factors in cosine bell
  polaris/ocean/convergence/__init__.py
  polaris/ocean/tasks/cosine_bell/__init__.py
  polaris/ocean/tasks/cosine_bell/decomp.py
  polaris/ocean/tasks/cosine_bell/restart/__init__.py
Labels: bug, ocean

#271 Don't include v0.1.0 in the docs
  docs/conf.py
  docs/developers_guide/ocean/framework.md
  docs/developers_guide/ocean/tasks/correlated_tracers_2d.md
  docs/developers_guide/ocean/tasks/divergent_2d.md
  docs/developers_guide/ocean/tasks/geostrophic.md
  docs/developers_guide/ocean/tasks/inertial_gravity_wave.md
  docs/developers_guide/ocean/tasks/manufactured_solution.md
  docs/developers_guide/ocean/tasks/nondivergent_2d.md
  docs/developers_guide/ocean/tasks/rotation_2d.md
Labels: documentation

#272 Update Polaris logo
  docs/_static/polaris_logo_rect.png
Labels: documentation
