Repository E3SM-Project/polaris, pull requests merged in 2025-03, with the labels that each got.

#288 Add `--account` to CTest instructions
  utils/omega/ctest/README.md
Labels: documentation

#289 Fix planar plots with log norm
  polaris/viz/planar.py
Labels: bug, framework

#291 Switch CI from miniconda to micromamba
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  deploy/shared.py
Labels: ci
